USE [DB_CONSULTORIO]
GO
/****** Object:  StoredProcedure [SCH_ADMIN].[SP_INSERTAR_CLIENTES]    Script Date: 18/4/2023 18:10:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [SCH_ADMIN].[SP_ELIMINAR_CLIENTES]
(@ID INT)

AS

BEGIN

DELETE FROM [SCH_ADMIN].[CLIENTES]
      WHERE [ID_CLIENTE]=@ID
END

GO


