 USE [master]
GO

--CREANDO BASE DE DATOS
CREATE DATABASE [DB_CONSULTORIO]
GO

USE [DB_CONSULTORIO]
GO


--CREANDO LOS ESQUEMAS DE SEGURIDAD
CREATE SCHEMA [SCH_ADMIN]
GO

CREATE SCHEMA [SCH_GENERAL]
GO


---CREANDO TABLAS
--- NOTAS.
/*
REVISAR SI LOS ID POR CADA TABLA SE PUEDEN AUTOINCREMENTAR
*/

----  TABLA USUARIOS
CREATE TABLE [SCH_ADMIN].[USUARIOS]
(
[ID_USUARIO] INT IDENTITY(1,1) NOT NULL,
[NOMBRE_USUARIO] VARCHAR(50) NOT NULL,
[CONTRASEÑA_USUARIO] VARCHAR(50) NOT NULL,
CONSTRAINT [PK_USUARIO] PRIMARY KEY CLUSTERED
(
[ID_USUARIO] ASC
)
)
GO

---- TABLA ROLES

CREATE TABLE [SCH_ADMIN].[ROLES]
(
[ID_ROL] INT IDENTITY(1,1) NOT NULL,
[TIPO_ROL] VARCHAR(50) NOT NULL,
CONSTRAINT [PK_UROL] PRIMARY KEY CLUSTERED
(
[ID_ROL] ASC
)
)
GO

---- TABLA ROLES POR USUARIO

CREATE TABLE [SCH_ADMIN].[ROLES_POR_USUARIO]
(
[ID_USUARIO] INT NOT NULL,
[ID_ROL] INT NOT NULL,
)
GO

---- TABLA ESPECIALIDADES

CREATE TABLE [SCH_ADMIN].[ESPECIALIDADES]
(
[ID_ESPECIALIDAD] INT IDENTITY(1,1) NOT NULL,
[NOMBRE_ESPECIALIDAD] VARCHAR(50) NOT NULL,
CONSTRAINT [PK_ESPECIALIDAD] PRIMARY KEY CLUSTERED
(
[ID_ESPECIALIDAD] ASC
)
)
GO

---- TABLA DOCTORES

CREATE TABLE [SCH_ADMIN].[DOCTORES]
(
[ID_DOCTOR] INT  IDENTITY(1,1) NOT NULL,
[ID_ESPECIALIDAD] INT NOT NULL,
[NOMBRE_DOCTOR] VARCHAR(50) NOT NULL,
[APELLIDO1_DOCTOR] VARCHAR(50) NOT NULL,
[APELLIDO2_DOCTOR] VARCHAR(50) NOT NULL,
[TELEFONO_DOCTOR] VARCHAR(50) NOT NULL,
[CORREO_DOCTOR] VARCHAR(50) NOT NULL,
[ID_USUARIO] INT NOT NULL,
CONSTRAINT [PK_DOCTOR] PRIMARY KEY CLUSTERED
(
[ID_DOCTOR] ASC
)
)
GO


---- TABLA SERVICIOS

CREATE TABLE [SCH_ADMIN].[SERVICIOS]
(
[ID_SERVICIO] INT IDENTITY(1,1) NOT NULL, 
[ID_ESPECIALIDAD] INT NOT NULL,
[COSTO_SERVICIO] INT NOT NULL,
[DETALLE_SERVICIO] VARCHAR(100) NOT NULL,
CONSTRAINT [PK_SERVICIO] PRIMARY KEY CLUSTERED
(
[ID_SERVICIO] ASC
)
)
GO

---- TABLA CLIENTES

CREATE TABLE [SCH_ADMIN].[CLIENTES]
(
[ID_CLIENTE] INT NOT NULL,
[NOMBRE_CLIENTE] VARCHAR(50) NOT NULL,
[APELLIDO1_CLIENTE] VARCHAR(50) NOT NULL,
[APELLIDO2_CLIENTE] VARCHAR(50) NOT NULL,
[DIRECCION_CLIENTE] VARCHAR(100) NOT NULL,
[TELEFONO_CLIENTE] VARCHAR(100) NOT NULL,
[CORREO_CLIENTE] VARCHAR(100) NOT NULL,
CONSTRAINT [PK_CLIENTE] PRIMARY KEY CLUSTERED
(
[ID_CLIENTE] ASC
)
)
GO

---- TABLA CITAS

CREATE TABLE [SCH_ADMIN].[CITAS]
(
[ID_CITA] INT IDENTITY(1,1) NOT NULL,
[ID_CLIENTE] INT NOT NULL,
[ID_ESPECIALIDAD] INT NOT NULL,
[ID_DOCTOR] INT NOT NULL,
[FECHA] DATETIME NOT NULL,
CONSTRAINT [PK_CITAS] PRIMARY KEY CLUSTERED
(
[ID_CITA] ASC
)
)
GO

---- TABLA EXPEDIENTE

CREATE TABLE [SCH_ADMIN].[EXPEDIENTE]
(
[ID_EXPEDIENTE] INT IDENTITY(1,1) NOT NULL,
[ID_CLIENTE] INT NOT NULL,
[DETALLE] VARCHAR(100) NOT NULL,
[ID_DOCTOR] INT NOT NULL,
CONSTRAINT [PK_EXPEDIENTE] PRIMARY KEY CLUSTERED
(
[ID_EXPEDIENTE] ASC
)
)
GO

---- TABLA METODO PAGO

CREATE TABLE [SCH_ADMIN].[METODO_PAGO]
(
[ID_METODO_PAGO] INT IDENTITY(1,1) NOT NULL,
[NOMBRE_METODO_PAGO] VARCHAR(50) NOT NULL,
[DETALLE_METODO_PAGO] VARCHAR(50) NOT NULL,
CONSTRAINT [PK_METODO_PAGO] PRIMARY KEY CLUSTERED
(
[ID_METODO_PAGO] ASC
)
)
GO

----TABLA FACTURAS

CREATE TABLE [SCH_ADMIN].[FACTURAS]
(
[ID_FACTURA] INT IDENTITY(1,1) NOT NULL,
[ID_METODO_PAGO] INT NOT NULL,
[ID_CLIENTE] INT NOT NULL,
[TOTAL_NETO] FLOAT NOT NULL,
CONSTRAINT [PK_FACTURA] PRIMARY KEY CLUSTERED
(
[ID_FACTURA] ASC
)
)
GO

---- TABLA PROMOCIONES

CREATE TABLE [SCH_ADMIN].[PROMOCIONES]
(
[ID_PROMOCION] INT IDENTITY(1,1) NOT NULL,
[DETALLE_PROMOCION] VARCHAR(100) NOT NULL,
[MONTO_PROMOCION] FLOAT NOT NULL,
[ID_SERVICIO] INT NOT NULL,
CONSTRAINT [PK_PROMOCION] PRIMARY KEY CLUSTERED
(
[ID_PROMOCION] ASC
)
)
GO

---- TABLA DETALLE FACTURA

CREATE TABLE [SCH_ADMIN].[DETALLE_FACTURA]
(
[ID_DETALLE_FACTURA] INT IDENTITY(1,1) NOT NULL,
[ID_FACTURA] INT NOT NULL,
[ID_SERVICIO] INT NOT NULL,
CONSTRAINT [PK_DETALLE_FACTURA] PRIMARY KEY CLUSTERED
(
[ID_DETALLE_FACTURA] ASC
)
)
GO


-----  LLAVES FORANEAS

----- TABLA ROLES POR USUARIO

ALTER TABLE  [SCH_ADMIN].[ROLES_POR_USUARIO] WITH NOCHECK
ADD CONSTRAINT FK_ROL_POR_USUARIO_X_USUARIO
	FOREIGN KEY (ID_USUARIO)
	REFERENCES [SCH_ADMIN].[USUARIOS](ID_USUARIO)

GO

ALTER TABLE [SCH_ADMIN].[ROLES_POR_USUARIO] CHECK CONSTRAINT [FK_ROL_POR_USUARIO_X_USUARIO]
GO

ALTER TABLE  [SCH_ADMIN].[ROLES_POR_USUARIO] WITH NOCHECK
ADD CONSTRAINT FK_ROL_POR_USUARIO_X_ROL
	FOREIGN KEY (ID_ROL)
	REFERENCES [SCH_ADMIN].[ROLES](ID_ROL)

GO

ALTER TABLE [SCH_ADMIN].[ROLES_POR_USUARIO] CHECK CONSTRAINT [FK_ROL_POR_USUARIO_X_ROL]
GO
---- TABLA DOCTORES

ALTER TABLE [SCH_ADMIN].[DOCTORES]  WITH NOCHECK
ADD CONSTRAINT FK_DOCTORES_X_ESPECIALIDAD
	FOREIGN KEY (ID_ESPECIALIDAD)
	REFERENCES [SCH_ADMIN].[ESPECIALIDADES](ID_ESPECIALIDAD)

GO

ALTER TABLE [SCH_ADMIN].[DOCTORES]  CHECK CONSTRAINT [FK_DOCTORES_X_ESPECIALIDAD]

GO

ALTER TABLE [SCH_ADMIN].[DOCTORES] WITH NOCHECK
ADD CONSTRAINT FK_DOCTORES_X_USUARIO
	FOREIGN KEY (ID_USUARIO)
	REFERENCES [SCH_ADMIN].[USUARIOS](ID_USUARIO)

GO

ALTER TABLE [SCH_ADMIN].[DOCTORES]  CHECK CONSTRAINT [FK_DOCTORES_X_USUARIO]

GO

---- TABLA SERVICIOS

ALTER TABLE [SCH_ADMIN].[SERVICIOS] WITH NOCHECK
ADD CONSTRAINT FK_SERVICIOS_X_ESPECIALIDAD
	FOREIGN KEY (ID_ESPECIALIDAD)
	REFERENCES [SCH_ADMIN].[ESPECIALIDADES](ID_ESPECIALIDAD)

GO

ALTER TABLE [SCH_ADMIN].[SERVICIOS] CHECK CONSTRAINT [FK_SERVICIOS_X_ESPECIALIDAD]

GO

---- TABLA CITAS

ALTER TABLE [SCH_ADMIN].[CITAS] WITH NOCHECK
ADD CONSTRAINT FK_CITAS_X_CLIENTE
	FOREIGN KEY (ID_CLIENTE)
	REFERENCES [SCH_ADMIN].[CLIENTES](ID_CLIENTE)

GO

ALTER TABLE [SCH_ADMIN].[CITAS] CHECK CONSTRAINT [FK_CITAS_X_CLIENTE]

GO

ALTER TABLE [SCH_ADMIN].[CITAS] WITH NOCHECK
ADD CONSTRAINT FK_CITAS_X_ESPECIALIDAD
	FOREIGN KEY (ID_ESPECIALIDAD)
	REFERENCES [SCH_ADMIN].[ESPECIALIDADES](ID_ESPECIALIDAD)

GO

ALTER TABLE [SCH_ADMIN].[CITAS] CHECK CONSTRAINT [FK_CITAS_X_ESPECIALIDAD]

GO

ALTER TABLE [SCH_ADMIN].[CITAS] WITH NOCHECK
ADD CONSTRAINT FK_CITAS_X_DOCTOR
	FOREIGN KEY (ID_DOCTOR)
	REFERENCES [SCH_ADMIN].[DOCTORES](ID_DOCTOR)

GO

ALTER TABLE [SCH_ADMIN].[CITAS] CHECK CONSTRAINT [FK_CITAS_X_DOCTOR]

GO

---- TABLA EXPEDIENTE

ALTER TABLE [SCH_ADMIN].[EXPEDIENTE] WITH NOCHECK
ADD CONSTRAINT FK_EXPEDIENTE_X_CLIENTE
	FOREIGN KEY (ID_CLIENTE)
	REFERENCES [SCH_ADMIN].[CLIENTES](ID_CLIENTE)

GO

ALTER TABLE [SCH_ADMIN].[EXPEDIENTE] CHECK CONSTRAINT [FK_EXPEDIENTE_X_CLIENTE]

GO

ALTER TABLE [SCH_ADMIN].[EXPEDIENTE] WITH NOCHECK
ADD CONSTRAINT FK_EXPEDIENTE_X_DOCTOR
	FOREIGN KEY (ID_DOCTOR)
	REFERENCES [SCH_ADMIN].[DOCTORES](ID_DOCTOR)

GO

ALTER TABLE [SCH_ADMIN].[EXPEDIENTE] CHECK CONSTRAINT [FK_EXPEDIENTE_X_DOCTOR]

GO

----TABLA FACTURAS

ALTER TABLE [SCH_ADMIN].[FACTURAS] WITH NOCHECK
ADD CONSTRAINT FK_FACTURAS_X_METODO_PAGO
	FOREIGN KEY (ID_METODO_PAGO)
	REFERENCES [SCH_ADMIN].[METODO_PAGO](ID_METODO_PAGO)

GO

ALTER TABLE [SCH_ADMIN].[FACTURAS] CHECK CONSTRAINT [FK_FACTURAS_X_METODO_PAGO] 

GO

ALTER TABLE [SCH_ADMIN].[FACTURAS] WITH NOCHECK
ADD CONSTRAINT FK_FACTURAS_X_CLIENTE
	FOREIGN KEY (ID_CLIENTE)
	REFERENCES [SCH_ADMIN].[CLIENTES](ID_CLIENTE)

GO

ALTER TABLE [SCH_ADMIN].[FACTURAS] CHECK CONSTRAINT  [FK_FACTURAS_X_CLIENTE]

GO
---- TABLA PROMOCIONES

ALTER TABLE [SCH_ADMIN].[PROMOCIONES] WITH NOCHECK
ADD CONSTRAINT FK_PROMOCIONES_X_SERVICIO
	FOREIGN KEY (ID_SERVICIO)
	REFERENCES [SCH_ADMIN].[SERVICIOS](ID_SERVICIO)

GO

ALTER TABLE [SCH_ADMIN].[PROMOCIONES] CHECK CONSTRAINT [FK_PROMOCIONES_X_SERVICIO]


---- TABLA DETALLE FACTURA

ALTER TABLE [SCH_ADMIN].[DETALLE_FACTURA] WITH NOCHECK
ADD CONSTRAINT FK_DETALLE_FACTURA_X_FACTURA
	FOREIGN KEY (ID_FACTURA)
	REFERENCES [SCH_ADMIN].[FACTURAS]

GO

ALTER TABLE [SCH_ADMIN].[DETALLE_FACTURA]  CHECK CONSTRAINT [FK_DETALLE_FACTURA_X_FACTURA]

GO

ALTER TABLE [SCH_ADMIN].[DETALLE_FACTURA] WITH NOCHECK
ADD CONSTRAINT FK_DETALLE_FACTURA_X_SERVICIO
	FOREIGN KEY (ID_SERVICIO)
	REFERENCES [SCH_ADMIN].[SERVICIOS](ID_SERVICIO)

GO

ALTER TABLE [SCH_ADMIN].[DETALLE_FACTURA]  CHECK CONSTRAINT [FK_DETALLE_FACTURA_X_SERVICIO]
GO

--
-- SECUENCIAS PARA EL ID DE CADA TABLA
-- 
CREATE SEQUENCE [SCH_ADMIN].[SEQ_ID_CITA] START WITH 1 INCREMENT BY 1 MINVALUE 1;
--

--
CREATE SEQUENCE [SCH_ADMIN].[SEQ_ID_DETALLE_FACTURA] START WITH 1 INCREMENT BY 1 MINVALUE 1;
--
CREATE SEQUENCE [SCH_ADMIN].[SEQ_ID_DOCTOR] START WITH 1 INCREMENT BY 1 MINVALUE 1;
--
CREATE SEQUENCE [SCH_ADMIN].[SEQ_ID_ESPECIALIDAD] START WITH 1 INCREMENT BY 1 MINVALUE 1;
--
CREATE SEQUENCE [SCH_ADMIN].[SEQ_ID_EXPEDIENTE] START WITH 1 INCREMENT BY 1 MINVALUE 1;
--
CREATE SEQUENCE [SCH_ADMIN].[SEQ_ID_FACTURA] START WITH 1 INCREMENT BY 1 MINVALUE 1;
--
CREATE SEQUENCE [SCH_ADMIN].[SEQ_ID_METODO_PAGO] START WITH 1 INCREMENT BY 1 MINVALUE 1;
--
CREATE SEQUENCE [SCH_ADMIN].[SEQ_ID_PROMOCION] START WITH 1 INCREMENT BY 1 MINVALUE 1;
--
CREATE SEQUENCE [SCH_ADMIN].[SEQ_ID_ROL] START WITH 1 INCREMENT BY 1 MINVALUE 1;
--
CREATE SEQUENCE [SCH_ADMIN].[SEQ_ID_SERVICIO] START WITH 1 INCREMENT BY 1 MINVALUE 1;
--
CREATE SEQUENCE [SCH_ADMIN].[SEQ_ID_USUARIO] START WITH 1 INCREMENT BY 1 MINVALUE 1;
--
GO